// add_product.js
// Handles the product creation form on add_product.html

document.addEventListener('DOMContentLoaded', () => {
  const form = document.getElementById('addProductForm');
  if (!form) return;

  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    const name = document.getElementById('name').value.trim();
    const description = document.getElementById('description').value.trim();
    const price = parseFloat(document.getElementById('price').value);
    const category = document.getElementById('category').value.trim();
    const image = document.getElementById('image').value.trim();
    const tagsInput = document.getElementById('tags').value.trim();
    const available = document.getElementById('available').checked;

    const tags = tagsInput ? tagsInput.split(',').map(t => t.trim()) : [];

    const product = {
      // id will be generated by dataService.addProduct()
      name,
      description,
      price,
      category,
      image: image || 'assets/default.png',
      available,
      tags,
    };

    try {
      const saved = await window.dataService.addProduct(product);
      alert(`Produto "${saved.name}" adicionado com sucesso!`);
      form.reset();
    } catch (err) {
      console.error('Erro ao adicionar produto:', err);
      alert('Falha ao adicionar produto. Consulte o console para mais detalhes.');
    }
  });
});
